#numpy session coding mafia


In [8]:
import numpy as np


# Arrays in numpy


In [9]:
arr=np.array([1,2,3])
arr1=np.array([[1,2,3], [4,5,6]])


In [10]:
type(arr)
type(arr1)

numpy.ndarray

In [11]:
arr.ndim


1

In [13]:
arr1.shape



(2, 3)

In [14]:
arr.shape

(3,)

In [15]:
arr.size


3

In [16]:
arr.dtype

dtype('int32')

In [20]:
c=np.ones((3,4))
print (c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.arange?

In [32]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [33]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [36]:
arr1=np.array([[1,2,3,8],
              [4,5,6,7],
              [-2,0.5,7,9]])
print(arr1)

[[ 1.   2.   3.   8. ]
 [ 4.   5.   6.   7. ]
 [-2.   0.5  7.   9. ]]


In [40]:
shap=arr1.reshape((4,3))
print(shap)

[[ 1.   2.   3. ]
 [ 8.   4.   5. ]
 [ 6.   7.  -2. ]
 [ 0.5  7.   9. ]]


In [41]:
arr1.max()

9.0

In [42]:
arr1.max(axis=1)

array([8., 7., 9.])

In [44]:
arr.max(axis=0)

3

In [45]:
arr1.min()

-2.0

In [46]:
arr1.min(axis=1)

array([ 1.,  4., -2.])

In [47]:
arr1.min(axis=0)

array([-2. ,  0.5,  3. ,  7. ])