# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)

1.18.1


#### 3. Create a null vector of size 10

In [4]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4.  How to find the memory size of any array

In [7]:
n=np.zeros((10,10))
print('%d bytes'%(n.size *n.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [12]:
m=np.arange(10,49)
print(m)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last)

In [13]:
print(m[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [17]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [34]:
np.random.uniform((3,3,3))

array([2.03159467, 2.82847971, 2.56387762])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [33]:
b=np.random.random((10,10))
print(b)
bmin=b.min()
bmax=b.max()
print(bmin)
print(bmax)

[[0.66318482 0.05109524 0.1651721  0.97249146 0.66840475 0.20945917
  0.65103236 0.73729682 0.77312646 0.59493626]
 [0.82534743 0.16170816 0.53314879 0.62188396 0.69074148 0.68821171
  0.38483502 0.67196392 0.16282477 0.17416237]
 [0.79161111 0.66105011 0.79667575 0.35676779 0.2274199  0.87079828
  0.69009206 0.26500468 0.83034875 0.04533763]
 [0.4371027  0.92082718 0.26767389 0.42401328 0.92929591 0.0340306
  0.5709498  0.82966474 0.72651922 0.29979912]
 [0.61971255 0.98532158 0.143637   0.48237771 0.29899247 0.41220398
  0.63581309 0.81443392 0.50101891 0.46109086]
 [0.90017018 0.86640169 0.91813813 0.2739553  0.72799595 0.93306113
  0.25331837 0.38453583 0.00124826 0.24764245]
 [0.39127037 0.82388391 0.46201869 0.27110071 0.69634083 0.63104114
  0.1034526  0.80221296 0.43957298 0.03621432]
 [0.23611908 0.48247121 0.46516641 0.82149317 0.37778292 0.26343245
  0.824339   0.75535594 0.8517575  0.78072217]
 [0.98560095 0.39738514 0.09344531 0.13044165 0.1355686  0.83479012
  0.7735863  

#### 14. Create a random vector of size 30 and find the mean value

In [27]:
c=np.random.random((30))
print(c)
np.mean(c)

[0.43309191 0.58531684 0.75211138 0.0864834  0.43764322 0.38127921
 0.21907896 0.45898637 0.3446815  0.1850155  0.45283961 0.24600845
 0.01677879 0.58196234 0.6894555  0.85579235 0.08484397 0.95525638
 0.78159321 0.59875025 0.87524875 0.62130489 0.74648746 0.10532076
 0.69444587 0.41536351 0.74139007 0.96555204 0.12444281 0.53829929]


0.4991608200752275

#### 15. Create a 2d array with 1 on the border and 0 inside

In [28]:
a=np.ones((5,5))
print(a)
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [29]:
x=np.ones((3,3))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf >np.nan)
print(np.nan -np.nan)
print(np.nan in set ([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
y=np.diag(1+np.arange(4), k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [43]:
p=np.zeros((8,8))
print(p)
p[1::2, ::2]=1
p[::2, 1::2]=1
print(p)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)